### ISSUE TITLE
onClickBackdrop does not register

### ISSUE THREAD

**Issue by stahlmanDesign** [nbudin/react-bootstrap4-modal#1]
Hi, works great except I'm not able to get the onClickBackdrop method to recognize a click. Looked at source code and not sure what's wrong.

**Comment by stahlmanDesign** [comment]
OK, I see that the modal with classNames fade and show has display: block on top of the backdrop. This is preventing the click event from registering. If I make the modal display: none (to test) I can then correctly click on the backdrop.

**Comment by nbudin** [comment]
Thanks for the bug report!  From a more thorough reading of the Bootstrap JS code than I'd initially done, it looks like I needed to register a click handler on the modal div itself (which is what Bootstrap does) and do some stopPropagation shenanigans to prevent clicks in the modal from bubbling up to the backdrop.

**Comment by nbudin** [comment]
This fix is now released as version 1.1.1.

**Comment by stahlmanDesign** [comment]
Nice! Confirmed that it is fixed

**Comment by nbudin** [comment]
Great!  Glad to hear it.
