### ISSUE TITLE
document is not defined

### ISSUE THREAD

**Issue by orszaczky** [nbudin/react-bootstrap4-modal#10]
I tried to add the example modal to my project, and I'm getting this error:

document is not defined ReferenceError: document is not defined
    at modalWillShow (node_modules\react-bootstrap4-modal\lib\index.js:1426:5)
    at Modal._this.componentWillMount (node_modules\react-bootstrap4-modal\lib\index.js:1450:9)

**Comment by orszaczky** [comment]
This was due to server-side rendering, i solved it by adding:

{typeof window !== 'undefined' &&
    <Modal....

**Comment by nbudin** [comment]
Thanks for the bug report @orszaczky!  I've added a small workaround for this to help support server-side rendering.  Could you try updating to version 1.3.1-pre1 and let me know if it allows you to remove that line?

**Comment by nbudin** [comment]
This fix is now released in 1.4.0.
