### ISSUE TITLE
Stacked modals

### ISSUE THREAD

**Issue by paulodeon** [nbudin/react-bootstrap4-modal#11]
Would you consider merging something like https://github.com/paulodeon/react-bootstrap4-modal/commit/b83a084b07f9e9c044b705a6271e88ba1b1a3efc in to allow for stacked modals with the backdrops over the lower modals?

**Comment by paulodeon** [comment]
https://getbootstrap.com/docs/4.0/layout/overview/#z-index 

1040 is the bootstrap modal _backdrop_ default z-index
1050 is the bootstrap modal default z-index

We are obviously interleaving them

In theory that would allow us 10 stacked modals, which should be enough

**Comment by paulodeon** [comment]
Still might make sense to allow configuration via a prop

**Comment by nbudin** [comment]
Aha, that makes sense.  Yeah, make a PR so I can merge it?

**Comment by nbudin** [comment]
This is now released in 1.4.0.
