### ISSUE TITLE
No fade-in animation on usage

### ISSUE THREAD

**Issue by nikeee** [nbudin/react-bootstrap4-modal#13]
Using Chrome and Firefox, there is no fade-in animation when opening the modal.

I think this has to do with `requestAnimationFrame(...)` in `Modal.jsx`. If i change it to `setTimeout(..., 16)`, the fade-in animation works.

**Comment by nbudin** [comment]
Thanks!  I'd noticed this but I hadn't been able to figure out why it wouldn't be working.

Normally I'd rather avoid `setTimeout` but it seems like for something that actually does take a known amount of time (like an animation), it's probably fine.  I'll see about changing it.

**Comment by nbudin** [comment]
This is now released in version 1.5.0.

**Comment by nikeee** [comment]
Thanks!
