### ISSUE TITLE
className for Modal is not adding

### ISSUE THREAD

**Issue by thidasapankaja** [nbudin/react-bootstrap4-modal#21]
I'm using "react-bootstrap4-modal": "1.1.2", in a project.

I tried to add `className='modal-dialog-centered'` to the Modal component to center it on the screen.

```
<Modal visible={showModal} onClickBackdrop={this.onCloseActionModal} className="modal-dialog-centered">
....content
 </div>
```

However when the component renders, the class is not added. But I tried using the class in the rendered component in chrome devtools and then the modal get centered. How can I fix this and get this working ? Or is there anyway I can center the modal in the screen ?

**Edit:** Tried with `dialogClassName="modal-dialog-centered"` as well. But still the same, it's not applying. When I open the modal in chrome devtools it displays like this

`<div class="modal-dialog" role="document"></div>`

**Comment by nbudin** [comment]
The ability to add className and dialogClassName was added in 1.2.0, so it's not in 1.1.2.  If you upgrade, it should work.
