### ISSUE TITLE
Scrolling the background instead of the modal

### ISSUE THREAD

**Issue by peterbe** [nbudin/react-bootstrap4-modal#3]
Thanks for a create lib! It works. The only problem is that scrolling doesn't work. When my modal window is really really tall, when I scroll (using the trackpad) it scrolls the "parent window" instead.

**Comment by peterbe** [comment]
When you open one of the modals here: https://getbootstrap.com/docs/4.0/components/modal/ and scrolling does not happen. Because the "focus" is on the modal window I guess. 

Any idea how to solve this?

**Comment by peterbe** [comment]
I fixed this by doing this:
```
  componentWillMount() {
    document.body.classList.add('modal-open')
  }

  componentWillUnmount() {
    this.dismounted = true
    document.body.classList.remove('modal-open')
  }
```

**Comment by nbudin** [comment]
Thanks for the bug report and the suggested fix!  I just wanted to drop a quick note to let you know I’ve been traveling, so I won’t be able to get to this quickly, but I’ll try to get this fixed when I’m back home.

**Comment by Nahasean94** [comment]
@peterbe where do you add that code? and what is this.dismounted used for?

**Comment by nbudin** [comment]
Oh man I dropped the ball on this hard.  Sorry about that!

I'll try and get this patched and released today.

**Comment by Nahasean94** [comment]
Also how to i change the size of the modal? I am displaying an image on the modal and the image size is larger than the modal so it bleeds out of the edges of the modal.

**Comment by peterbe** [comment]
@Nahasean94 That's in any react component which, when rendered tries to make the model object. E.g. 
```jsx
class MyReactModal extends React.Component {
    render() {
        ...render the modal container...
    }
}
```

That `this.dismounted` is not relevant. Sorry. It's a thing I use to avoid calling `this.setState()` in an async callback if the whole component has been unmounted.

**Comment by nbudin** [comment]
react-bootstrap4-modal version 1.1.2 is now released with a fix for the scrolling issue.

@Nahasean94: In the content of your modal, you can include a `modal-dialog` div with a sizing class, as shown here: https://getbootstrap.com/docs/4.0/components/modal/#optional-sizes

**Comment by Nahasean94** [comment]
@nbudin Thanks a lot...All is well now!!
